server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ems_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
