server:
  port: 9999
spring:
#  datasource:
#    url: jdbc:mysql://mysql-3667c571-codeloom4-emsdb.k.aivencloud.com:13372/defaultdb
#    username: avnadmin
#    password: AVNS_EGn8V0ttbUNcdQYNfxm
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 10
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ems_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Cross-Origin Resource Sharing configurations
cors:
  uris:
    - http://localhost:5000
    - https://localhost:5000
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
